
import { TextEdit, ScrollView } from "std-widgets.slint";
export component App inherits Window {
    height: 300px;
    width: 1024px;
    title: "hAACs Runtime";

    Rectangle {
        background: #303030;
        border-color: #ff0000;
        border-radius: 2px;
        border-width: 2px;
        height: 55px;
        y: 0cm; }
    Rectangle {
        border-color: #00ff04;
        border-width: 2px;
        height: 245px;
        width: 450px;
        x: 0px;
        y: 55px;
    }
    Rectangle {
        border-color: #00ff04;
        border-width: 2px;
        height: 245px;
        width: 450px;
        x: 574px;
        y: 55px; }
    Rectangle {
        border-color: #00ddff;
        border-width: 2px;
        height: 245px;
        width: 124px;
        x: 450px;
        y: 55px; }
}