import { Carousel } from "carousel.slint";
import { CarouselTheme } from "carousel_theme.slint";
import { CarouselWidget } from "carousel_widget.slint";

export component MainMenu inherits Rectangle {
    background: #383838;
    height: 600px;
    width: 1024px;

    Rectangle {
        height: 100px;
        width: 1024px;
        y: 0px;
        x: 0px;
        z: 2;
        background: #000000;
        Text {
            color: #ffffff;
            font-size: 50px;
            horizontal-alignment: TextHorizontalAlignment.center;
            letter-spacing: 5px;
            text: "hAACs";
            vertical-alignment: TextVerticalAlignment.center;
        }
    }

    private property <[{ title: string, image: image}]> navigation-items: [
           { title: "AAC", image: @image-url("svg/settings_black.svg") },
           { title: "Game", image: @image-url("svg/home_black.svg") },
           { title: "Settings", image: @image-url("svg/info_black.svg") },
        ];
    private property <int> selected-index: 1;

    carousel := Carousel {
            y: 50px;
            height: 100%;
            itemWidth: CarouselTheme.size-medium;
            count: root.navigation-items.length;
            selected-index <=> root.selected-index;
            spacing: CarouselTheme.spacing-medium;

            for item[index] in root.navigation-items : CarouselWidget {
                clicked => { root.selected-index = index; }

                is-selected: index == root.selected-index;
                opacity: self.is-selected ? CarouselTheme.opacity-big : CarouselTheme.opacity-medium;
                title: item.title;
                image-source: item.image;
                y: (parent.height - self.height) / 2;
            }
        }
}