export component MainMenuWidget {

    widget := Rectangle {
        background: #6b6b6b;
        border-radius: 20px;
        drop-shadow-blur: 75px;
        drop-shadow-color: #0062ff;
        drop-shadow-offset-x: 0px;
        drop-shadow-offset-y: 0px;
        height: 300px;
        opacity: 1;
        visible: true;
        width: 300px;

        Text {
            color: #ffffffff;
            font-size: 20px;
            horizontal-alignment: TextHorizontalAlignment.center;
            opacity: 1;
            text: "Example Widget";
            vertical-alignment: TextVerticalAlignment.center;
            x: 80px;
            y: 25px;
            z: 2;
        }
    }

    public function set_selected(selected: bool) {
        widget.drop-shadow-blur = selected ? 75px : 0px;
        widget.opacity = selected ? 1 : 0.3;
        widget.width = selected ? 300px : 100px;
        widget.height = selected ? 300px : 100px;
    }
}