import { Carousel } from "widgets/carousel/carousel.slint";
import { CarouselTheme } from "widgets/carousel/carousel_theme.slint";
import { CarouselWidget } from "widgets/carousel/carousel_widget.slint";
import { BasicScreen } from "basic_screen.slint";

export component MainMenu inherits BasicScreen {
    Rectangle {
        height: 100px;
        width: 1024px;
        y: 0px;
        x: 0px;
        z: 2;
        background: #000000;
        Text {
            color: #ffffff;
            font-size: 50px;
            horizontal-alignment: TextHorizontalAlignment.center;
            letter-spacing: 5px;
            text: "hAACs";
            vertical-alignment: TextVerticalAlignment.center;
        }
    }

    private property <[{ title: string, image: image}]> navigation-items: [
           { title: "AAC", image: @image-url("images/aac.png") },
           { title: "Alphabet Game", image: @image-url("images/alphabet.png") },
           { title: "Settings", image: @image-url("images/settings.png") },
        ];
    private property <int> selected-index: 1;

    carousel := Carousel {
            y: 50px;
            height: 100%;
            itemWidth: CarouselTheme.size-medium;
            count: root.navigation-items.length;
            selected-index <=> root.selected-index;
            spacing: CarouselTheme.spacing-medium;

            for item[index] in root.navigation-items : CarouselWidget {
                clicked => {
                    if (root.selected-index == index) {
                        carousel_clicked(index);
                    } else {
                        root.selected-index = index;
                    }
                }

                is-selected: index == root.selected-index;
                opacity: self.is-selected ? CarouselTheme.opacity-big : CarouselTheme.opacity-medium;
                title: item.title;
                image-source: item.image;
                y: (parent.height - self.height) / 2;
            }
    }

    callback carousel_clicked(index: int);
}