import { BasicScreen } from "basic_screen.slint";
import { HomeButton } from "widgets/home_button/home_button.slint";
import { Format } from "data/format.slint";
import { Slider, ComboBox } from "std-widgets.slint";
import { KeyboardCallback, Keyboard } from "callback/keyboard_callbacks.slint";
import { AACCallback } from "callback/aac_callbacks.slint";
import { SettingsData } from "data/settings_data.slint";
export component SettingsMenu inherits BasicScreen {
    HomeButton {
        clicked => {
            root.return_to_main_menu();
        }
    }

    Text {
        x: 0;
        y: 10px;
        width: 100%;
        height: 75px;
        text: "Settings";
        vertical-alignment: center;
        horizontal-alignment: center;
        font-size: 24px;
    }

    Rectangle {
        width: 400px;
        height: 75px;
        x: 20px;
        y: 85px;
        border-radius: 8px;
        border-color: black;
        border-width: 2px;
        Text {
            x: 0px;
            y: 0px;
            height: 50px;
            width: 100%;
            text: "AAC Font";
            horizontal-alignment: center;
            vertical-alignment: center;
            font-size: Format.aac_font_size;
        }
        Slider {
            height: 20px;
            width: 90%;
            x: 20px;
            y: 40px;
            value: Format.aac_font_size / 1px;
            minimum: 10;
            maximum: 30;
            step: 1;
            changed(value) => {
                Format.aac_font_size = value * 1px;
            }
        }
    }

    Rectangle {
            width: 400px;
            height: 75px;
            x: 20px;
            y: 180px;
            border-radius: 8px;
            border-color: black;
            border-width: 2px;
            Text {
                x: 0px;
                y: 0px;
                height: 50px;
                width: 100%;
                text: "Keyboard";
                horizontal-alignment: center;
                vertical-alignment: center;
                font-size: 18px;
            }
            ComboBox {
                height: 20px;
                width: 90%;
                x: 20px;
                y: 40px;
                model: ["Default", "Swipe", "USB"];
                current-value: "Default";
                selected(current-value) => {
                    if (current-value == "Default") {
                        KeyboardCallback.current_keyboard = Keyboard.Standard;
                    } else if (current-value == "Swipe") {
                        KeyboardCallback.current_keyboard = Keyboard.Swipe;
                    } else {
                        KeyboardCallback.current_keyboard = Keyboard.None;
                    }
                }
            }
        }

        Rectangle {
                    width: 400px;
                    height: 75px;
                    x: 20px;
                    y: 275px;
                    border-radius: 8px;
                    border-color: black;
                    border-width: 2px;
                    Text {
                        x: 0px;
                        y: 0px;
                        height: 50px;
                        width: 100%;
                        text: "AAC Voices";
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        font-size: 18px;
                    }
                    ComboBox {
                        height: 20px;
                        width: 90%;
                        x: 20px;
                        y: 40px;
                        model: AACCallback.voices;
                        current-value: AACCallback.voices[0];
                        selected(current-value) => {
                            AACCallback.set_voice(current-value);
                        }
                    }
        }

   Rectangle {
            width: 400px;
            height: 75px;
            x: 20px;
            y: 370px;
            border-radius: 8px;
            border-color: black;
            border-width: 2px;
            Text {
                x: 0px;
                y: 0px;
                height: 50px;
                width: 100%;
                text: "Audio Output";
                horizontal-alignment: center;
                vertical-alignment: center;
                font-size: 18px;
            }
            ComboBox {
                height: 20px;
                width: 90%;
                x: 20px;
                y: 40px;
                model: SettingsData.bluetooth_devices;
                current-value: "Speakers";
                selected(current-value) => {
                    SettingsData.set_bluetooth_audio_device(current-value);
                }
            }
        }
}